import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Roboto_Slab , Noto_Serif_Khmer } from "next/font/google";

const robotoslab = Roboto_Slab({
  subsets: ["latin"],
  weight: "300"
});
const khmerFont = Noto_Serif_Khmer({
  subsets: ["latin"],
  weight: "300"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProp{
  children: React.ReactNode;
  params : {
    locale : string;
  }
}

export default function RootLayout({
  children,
  params : {locale}
}: Readonly<RootLayoutProp>) {
  const activeFontClass =
  locale === "kh" ? khmerFont.className : robotoslab.className;
  return (
    <html lang={locale}>
      <body
        className={activeFontClass}
      >
        <div className="flex flex-col min-h-screen">
          <Header></Header>
          <div className="flex-grow">{children}</div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
